### ISSUE TITLE
InertialFlowCutter: Lat and Lon in correct format

### ISSUE THREAD

**Issue by paulheinr** [Janekdererste/rust_q_sim#10]
See src/routing/network_converter.rs:47 

Open questions: 
* Which coordinate system is used for InertialFlowCutter? Does InertialFlowCutter use coordinates at all?
* How to pass float values? 

Right now, lat and lon vector is calculated by flooring the correct values.

**Comment by paulheinr** [comment]
Idea: run following commands on console

load_dimacs_geo_pos
save_binary_geo_pos

**Comment by paulheinr** [comment]
The InertialFlowCutter expects coordinates in dimacs format (see: http://www.diag.uniroma1.it/challenge9/format.shtml). 
They are WGS84 coordinates in decimal format with a scale factor of 1,000,000. So e.g. `52.525444, 13.320802` will be stored in the dimacs file as `v 1 52525444 13320802`. 
In case there is no function provided by the InertialFlowCutter console, one can got the way 
1. save file in dimacs geo position in rust
2. load this file in console 
3. save geo pos as binary

**Comment by paulheinr** [comment]
Best option: use `text_to_binary_float_vector`

**Comment by Janekdererste** [comment]
I don't see the specification for the format on that page. Can you give a more specific link? Also, if the coordinates have to be WGS84, you can't translate our coordinates into those of the format. WGS84 is spheric CRS, working with lon/lat, while MATSim uses euclidean CRS such as UTM. I didn't see anything about that requirement either.

In case WGS84 is required you need a transformation from one CRS into the other.

**Comment by paulheinr** [comment]
Unfortunately its not very well documented. I've made these findings by reverse engineering. The scaling factor (1,000,000) is defined in the c++ code of the InertialFlowCutter. Moreover, they use "latitude" and "longitude" as coordinate names. The coordinates of the dimacs examples are WGS84. I used an online map to verify this. 
Unfortunately, in their paper of the "InertialFlowCutter", they do not specify the coordinate system. I will ask that in their repository. 

Eventually, that issue does not have high priority I guess. If we use non-sense coordinates as input of the InertialFlowCutter, the ordering is not helpful with respect to computation times of routing requests. Nevertheless, the resulting path should always be valid and optimal.

**Comment by paulheinr** [comment]
Since the original issue (only long and no floats as lat and long) is already fixed, it declared this issue as enhancement.

**Comment by paulheinr** [comment]
Submitted an issue to the repository of InertialFlowCutter: https://github.com/kit-algo/InertialFlowCutter/issues/14

**Comment by paulheinr** [comment]
The InertialFlowClutter expects Euclidean coordinates. Since in standard MATSim we do also expect those coordinates, there is no problem. The terms `latitude` and `longitude` should no longer be used in our code (except in `src/simulation/routing/inertial_flow_cutter_adapter.rs` because it expects so called files)
