### ISSUE TITLE
Re-introduce unit tests for simulation

### ISSUE THREAD

**Issue by Janekdererste** [Janekdererste/rust_q_sim#114]
Because I didn't know how to resolve that immediately, I decided to take out unit tests in `simulation.rs` think about how to re-introduce those tests. 

Also, I would prefer only one variant of `execute_qsim`. As far as I am concerned, we can also execute the single partition Qsim in another thread. This test is there to make sure that the overall simulation logic, without messaging, works correctly.

**Comment by Janekdererste** [comment]
This was done in commit https://github.com/Janekdererste/rust_q_sim/commit/96aeaa574aeff7e421b87f7297264f8d0444b1b4

**Comment by paulheinr** [comment]
Is it? Tests are still commented out.
