### ISSUE TITLE
Github acitons: Make InertialFlowCutterAdapter work

### ISSUE THREAD

**Issue by paulheinr** [Janekdererste/rust_q_sim#15]
With #24, adhoc routing will be implemented. For now tests that compute a node ordering at any point in time, will be ignored by github actions because the InertialFlowCutter package needs to be installed. 

However, those tests should work on github actions.

**Comment by Janekdererste** [comment]
Is the commented out stuff https://github.com/Janekdererste/rust_q_sim/blob/28b6a3211fb94afa55a26a59fa918e5438aa1d8c/.github/workflows/rust.yml#L13 related to his?

**Comment by paulheinr** [comment]
It is. That was my first try, which didn't work, but I didn't want to throw it away.
