### ISSUE TITLE
Run integration tests with ci and mpi

### ISSUE THREAD

**Issue by Janekdererste** [Janekdererste/rust_q_sim#38]
Maybe this is related to #36 . If we use the mpi-based simulation from now on, we need to run the integration tests within `mpirun`, to provide the message passing context. This can be done in a similar fashion as the [rsmpi-project](https://github.com/rsmpi/rsmpi) does it. 

- See their [ci-script](https://github.com/rsmpi/rsmpi/blob/22fed82196f3daba1741b3f781dfa7e11ebdc033/.github/workflows/test.yaml#L72)
- And the [script](https://github.com/rsmpi/rsmpi/blob/main/ci/run-examples.sh) which gets executed by above build-step

**Comment by Janekdererste** [comment]
This is related to #36 . Probably this can be done in one go.

**Comment by Janekdererste** [comment]
@paulheinr is this done with #49? You cold close this issue if so.

**Comment by paulheinr** [comment]
Done with #49
