### ISSUE TITLE
change master to main

### ISSUE THREAD

**Issue by Janekdererste** [Janekdererste/rust_q_sim#45]
it's 2023

**Comment by paulheinr** [comment]
I'm not able to do so because I can't change the settings. But here is an instruction how to change it: https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab

**Comment by Janekdererste** [comment]
I would have just branched off a main branch, changed all the protection and ci rules to main and then deleted the master branch.

**Comment by paulheinr** [comment]
Yes, that's essentially what the instruction recommends, but I'm not allowed to change the protection and delete the master branch 🙃 I just wanted to inform you that I can't take that issue

**Comment by Janekdererste** [comment]
So, I did the following things

- Create Branch `main`
- Set Ci-Rules to `main`
- Make `main` default branch of the github repo
- Make `main` protected branch and rquire PR with passing build before merging
- Change all (2) PRs to be merged into `main`
- Delete old branches includeing `master`

Locally:
- Delete all branches exept `main`
- Give it a star in Clion to mark it special

I think, this is done.
