### ISSUE TITLE
Confusing file names network_partition.rs and partitioned_network.rs

### ISSUE THREAD

**Issue by paulheinr** [Janekdererste/rust_q_sim#52]
Both files are called very similar. 

`network_partition.rs` consists of the `NetworkPartition` struct itself. `partitioned_network.rs` consists of the `Network` struct. I suggest that either both files should have more different names or they should be merged into one file

**Comment by Janekdererste** [comment]
Yes, good point

**Comment by paulheinr** [comment]
I see. What about renaming `partitioned_network` to `network`? Small downside is that the module, where all these files are placed, is also called `network`.

**Comment by Janekdererste** [comment]
Do it!
