### ISSUE TITLE
IntertialFlowCutter dependency can't be build on Ubuntu 22.04

### ISSUE THREAD

**Issue by Janekdererste** [Janekdererste/rust_q_sim#71]
When I try to follow the instructions from the router readme, I can't build the IntertialFlowCutter dependency. I receive the following error
```
janek@janek-ms7c02:~/projects/InertialFlowCutter/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
ERROR: Intel TBB NOT found!
-- Looked for Threading Building Blocks in /opt/intel/tbb;/usr/local/include;/usr/include
CMake Error at cmake/FindTBB.cmake:272 (message):
  Could NOT find TBB library.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)
```
I also filed an issue in the original repository https://github.com/kit-algo/InertialFlowCutter/issues/13 . 

@paulheinr what to do?

**Comment by Janekdererste** [comment]
I guess this is related to the wrong cmake version mentioned [here](https://github.com/paulheinr/InertialFlowCutter#building)?

**Comment by Janekdererste** [comment]
In case you figure something out it would be great to switch the test environment to ubuntu lts 22.04 and add the cmake version step into the build script. This is the place where I usually peek to set up the project 🙃

**Comment by paulheinr** [comment]
Thanks for submitting the Issue at the original repository. They fixed it. I merged the changes in my custom InertialFlowCutter repository. When I tried it out on WSL with both Ubuntu 20 and Ubuntu 22 it works now ✈️
