### ISSUE TITLE
Affinity Crate does not support macOs

### ISSUE THREAD

**Issue by Janekdererste** [Janekdererste/rust_q_sim#94]
Trying to get started on macOS, the following error occurs when execution `cargo build`
```
error: macros that expand to items must be delimited with braces or followed by a semicolon
  --> /Users/janek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/affinity-0.1.2/src/lib.rs:43:9
   |
43 |         unimplemented!("This crate does not support your OS yet !");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `unimplemented` (in Nightly builds, run with -Z macro-backtrace for more info)
```
The crate is a dependency of `rust_road_router`.

This crate gives a lot of headaches...

**Comment by Janekdererste** [comment]
To keep working on this project on mac os as well, I will remove the routing part from the branch related to https://github.com/Janekdererste/rust_q_sim/pull/93 . 

I will not commit these changes to `main`, but keep an alternative `main` until @paulheinr has come up with a solution :-/

**Comment by paulheinr** [comment]
Uff, that doesn't look good. I don't know if there's a simple solution to this... I will look into it and see what I can do.
